project_id = "gglhrfogvwnrgyvlixjq"

[functions.seed-admin]
verify_jwt = false

[functions.admin-delete-business]
verify_jwt = false

[functions.initiate-subscription-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.mtn-momo-webhook]
verify_jwt = false

[functions.extend-subscription]
verify_jwt = false

[functions.lipila-webhook]
verify_jwt = false