// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://gglhrfogvwnrgyvlixjq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbGhyZm9ndnducmd5dmxpeGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NDA4ODgsImV4cCI6MjA5OTAxNjg4OH0.PYHVGEad_x7gpQZby6vaIfVUTb55qeRLIeFtptHLoXU';


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/**
 * Custom auth storage that isolates sessions per user so signing out of one
 * account doesn't affect another.  Sessions are stored in localStorage with
 * a user-ID suffix (e.g.  `sb-{ref}-auth-token-{userId}`).  A per-tab marker
 * in sessionStorage tracks which user this tab is using.
 *
 *   setItem → extracts user.id from the session JSON, writes `key-{userId}`
 *   getItem → reads `key-{activeUserId}`, falls back to scanning for any
 *             user-specific key or the legacy unprefixed key
 *   removeItem → removes `key-{activeUserId}` only (other users untouched)
 */
function buildMultiAccountStorage(): Storage {
  const ls = (() => {
    try { return localStorage; } catch { return null; }
  })();
  const ss = (() => {
    try { return sessionStorage; } catch { return null; }
  })();
  const ACTIVE_USER_KEY = 'zampos_active_user';
  const ACTIVE_USER_LS_KEY = 'zampos_active_user_ls';

  const getActiveUserId = (): string | null => {
    // 1) Try sessionStorage (normal path)
    if (ss) {
      try {
        const ssVal = ss.getItem(ACTIVE_USER_KEY);
        if (ssVal) return ssVal;
      } catch { /* noop */ }
    }
    // 2) Fallback: localStorage (survives Android tab kills)
    if (ls) {
      try {
        const lsVal = ls.getItem(ACTIVE_USER_LS_KEY);
        if (lsVal) {
          // Restore into sessionStorage so subsequent lookups are fast
          if (ss) {
            try { ss.setItem(ACTIVE_USER_KEY, lsVal); } catch { /* noop */ }
          }
          return lsVal;
        }
      } catch { /* noop */ }
    }
    return null;
  };

  const setActiveUserId = (id: string) => {
    // Write to both sessionStorage and localStorage
    if (ss) {
      try { ss.setItem(ACTIVE_USER_KEY, id); } catch { /* noop */ }
    }
    if (ls) {
      try { ls.setItem(ACTIVE_USER_LS_KEY, id); } catch { /* noop */ }
    }
  };

  const clearActiveUserId = () => {
    if (ss) {
      try { ss.removeItem(ACTIVE_USER_KEY); } catch { /* noop */ }
    }
    if (ls) {
      try { ls.removeItem(ACTIVE_USER_LS_KEY); } catch { /* noop */ }
    }
  };

  const lGet = (k: string): string | null => {
    if (!ls) return null;
    try { return ls.getItem(k); } catch { return null; }
  };
  const lSet = (k: string, v: string) => {
    if (!ls) return;
    try { ls.setItem(k, v); } catch { /* noop */ }
  };
  const lRemove = (k: string) => {
    if (!ls) return;
    try { ls.removeItem(k); } catch { /* noop */ }
  };

  return {
    get length() { return ls ? ls.length : 0; },
    clear() { if (ls) try { ls.clear(); } catch { /* noop */ } },
    key(index: number) { return ls ? ls.key(index) : null; },

    getItem(key: string): string | null {
      if (!key.includes('auth-token')) return lGet(key);

      // 1) Active user's specific key (sessionStorage → localStorage fallback)
      const activeId = getActiveUserId();
      if (activeId) {
        const val = lGet(`${key}-${activeId}`);
        if (val) return val;
      }

      // 2) Legacy unprefixed key – migrate on first read
      const legacy = lGet(key);
      if (legacy) {
        try {
          const session = JSON.parse(legacy);
          const uid: string | undefined = session?.user?.id ?? session?.user?.sub;
          if (uid) {
            lSet(`${key}-${uid}`, legacy);
            lRemove(key);
            setActiveUserId(uid);
          }
        } catch { /* ignore parse errors */ }
        return legacy;
      }

      // 3) Scan for any existing user-specific key (pick most recently updated)
      if (ls) {
        try {
          let bestKey: string | null = null;
          let bestTime = 0;
          for (let i = 0; i < ls.length; i++) {
            const k = ls.key(i);
            if (k?.startsWith(key + '-')) {
              const val = lGet(k);
              if (val) {
                // Parse to find the most recent session
                try {
                  const sess = JSON.parse(val);
                  const t = sess?.updated_at ? new Date(sess.updated_at).getTime() : 0;
                  if (t >= bestTime) {
                    bestTime = t;
                    bestKey = k;
                  }
                } catch {
                  // If can't parse, just use first match
                  if (!bestKey) bestKey = k;
                }
              }
            }
          }
          if (bestKey) {
            const userId = bestKey.slice(key.length + 1);
            setActiveUserId(userId);
            return lGet(bestKey);
          }
        } catch { /* ignore */ }
      }

      return null;
    },

    setItem(key: string, value: string): void {
      if (!key.includes('auth-token')) { lSet(key, value); return; }
      try {
        const session = JSON.parse(value);
        const userId: string | undefined = session?.user?.id ?? session?.user?.sub;
        if (userId) {
          lSet(`${key}-${userId}`, value);
          setActiveUserId(userId);
          return;
        }
      } catch { /* fall through to unprefixed */ }
      lSet(key, value);
    },

    removeItem(key: string): void {
      if (!key.includes('auth-token')) { lRemove(key); return; }
      const activeId = getActiveUserId();
      if (activeId) { lRemove(`${key}-${activeId}`); return; }
      lRemove(key);
    },
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: buildMultiAccountStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
